Catch errors when scraping datadir from help output
docker-library/percona pull request #27
Opened 2016-09-30 21:15 UTC by yosifkit

Before this change, a user would just get the container exiting and zero output. Now a user will get some friendly output about the command that was run and then the error messages that mysqld emitted.

See also https://github.com/docker-library/mysql/pull/218

2016-10-11 20:19 UTC, tianon commented
Are you planning to update this with the changes from docker-library/mysql#218, or would you rather be responsible for maintaining the delta? :smile: :wink:

2016-10-11 23:45 UTC, yosifkit commented
I'll be syncing all the changes tomorrow, so don't merge this or https://github.com/docker-library/mariadb/pull/84.

2016-10-12 23:18 UTC, yosifkit commented
Changes have been re-synced to this and https://github.com/docker-library/mariadb/pull/84 which also gets us the `shopt -s nullglob` from https://github.com/docker-library/mysql/pull/200.

2016-10-13 23:32 UTC, tianon requested changes

2016-10-13 23:32 UTC, tianon commented on 5.6/docker-entrypoint.sh
> +		mysql_install_db --datadir="$DATADIR" --rpm --keep-my-cnf
:wink:

2016-10-13 23:40 UTC, yosifkit commented on 5.6/docker-entrypoint.sh
> +		mysql_install_db --datadir="$DATADIR" --rpm --keep-my-cnf
done

2016-10-13 23:40 UTC, tianon approved these changes

2016-10-13 23:41 UTC, merged